MY_DB = "stocks_db"

INGESTION_TIMESERIES_TABLE = "ingestion_master_stock_table"
INGESTION_OVERVIEW_TABLE = "ingestion_master_overview_table"

TRANSFORMATION_CLEANED_TIMESERIES_TABLE = "transformation_cleaned_timeseries_table"
TRANSFORMATION_CLEANED_OVERVIEW_TABLE = "transformation_cleaned_overview_table"
TRANSFORMATION_BAD_TIMESERIES_TABLE = "transformation_bad_timeseries_table"
TRANSFORMATION_BAD_OVERVIEW_TABLE = "transformation_bad_overview_table"
TRANSFORMATION_DAILY_STOCK_PERFORMANCE_TABLE = "transformation_daily_stock_performance_table"
TRANSFORMATION_STOCK_MOVING_AVERAGES_TABLE = "transformation_stock_moving_averages_table"
TRANSFORMATION_SECTOR_PERFORMANCE_TABLE = "transformation_sector_performance_table"
